### ISSUE TITLE
[optimizations] 建议对代码进行一些优化

### ISSUE THREAD

**Issue by FoliageOwO** [GooGuJiang/Gugumoe-bot#6]
1. [optional] 因为随着 `python` 版本迭代，有些语法可能会发生变更，所以建议在 `README.md` 中添加 `python` 版本相关说明；
2. **[required] 对 `requirements.txt` 中的所需库的版本进行约束，有些库在更新后会改变函数、方法、类等，亦或是语法，一味的安装最新版可能会导致原代码报错，有必要进行约束。**

**Comment by GooGuJiang** [comment]
嗯，会注意的
